import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useState } from "react";
import styles from "@/styles/Home.module.css";
import AddTodo from "../../components/AddTodo";
import { Todo } from "../../components/AddTodo";
import TabGroup from "../../components/TabGroup";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const Logo = () => (
    <Image
      src="/images/todo-logo.png"
      alt="Todo Logo"
      width="160"
      height="79"
    />
  );

  return (
    <>
      <Head>
        <title>Todos via Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Logo />
        <TabGroup todos={todos} setTodos={setTodos} />
        <AddTodo setTodos={setTodos} />
      </main>
    </>
  );
}
